#
#
#
routing:
    homepage:
        path: /
        action: Ourframework\User\Controllers\SimpleController
    blog:
        path: /blog
        action: Ourframework\User\Controllers\BlogController
    blog_article:
        path: /blog/article/*
        action: Ourframework\User\Controllers\SimpleController
    blog_page:
        path: /blog/[page]/*
        action: Ourframework\User\Controllers\SimpleController
    admin:
        path: /admin
        action: Action4