#
#
#
routing:
    homepage:
        path: /
        action: Ourframework\User\Controllers\SimpleController
    blog:
        path: /blog/*
        action: Ourframework\User\Controllers\BlogController
    blog_art:
        path: /blog/{String}
        action: Ourframework\User\Controllers\StringRegexController
    blog_regex:
        path: /blog/{Number}
        action: Ourframework\User\Controllers\NumberRegexController
