#
# TODO
# For testing purpose we need to make huge routing file table consists of all possibility cases
# To do that I propose make .csv file and write special class for that which will implements Iterator interface
# Example: https://stackoverflow.com/questions/10646105/how-to-use-a-csv-file-in-phpunit-test
#
#
routing:
    homepage:
        path: /
        action: Ourframework\User\Controllers\SimpleController
    blog:
        path: /blog/art
        action: Ourframework\User\Controllers\BlogController
    blog_article:
        path: /blog
        action: Ourframework\User\Controllers\SimpleController
    blog_page:
        path: /blog/{Number}
        action: Ourframework\User\Controllers\BlogController
    blog_page_string:
        path: /blog/{String}
        action: Ourframework\User\Controllers\SimpleController
    blog_page_test1:
        path: /blog/blog/*/*
        action: Ourframework\User\Controllers\SimpleController
    admin:
        path: /admin
        action: Action4
    radek:
        path: /radek/{Number}
        action: Ourframework\User\Controllers\RadekController
    bartek:
        path: /radek/{String}/*/*/
        action: Ourframework\User\Controllers\BartekController
    coronavirus:
        path: /*/*/*
        action: Ourframework\User\Controllers\SimpleController
    coronavirus2:
        path: /*/*/*/*
        action: Ourframework\User\Controllers\SimpleController
    coronavirus3:
        path: /*/*/*/*/*
        action: Ourframework\User\Controllers\SimpleController