#
# TODO
# This file should be used to set all paths and important variables
# But for now this is unused
# Someone has to write class(or methods in SettingsManager) to manage those variables and paths
#
settings:
    core:
        routing: "Config/routing.yaml"
        template_path: "User/Templates/"
        dsn:
    template:
        engine: ['twig'] # or twig, blade, smarty etc.
    relative_paths:
        -
    absolute_paths:
        -
