settings:
    core:
        routing: "Config/routing.yaml"
        tempalate_path: "User/Templates/"
        dsn:
    database:
        host:
        password:
        engine:
    relative_paths:
        -
    absolute_paths:
        -
